### ISSUE TITLE
what happened to me?

### ISSUE THREAD

**Issue by valleykid** [shuhei/babel-plugin-null-safe-accessor#1]
```
$ babel-node test/index.js
```

test/index.js is  from your unit folder, I moved it and .babelrc into a new folder, and npm install `babel-plugin-null-safe-accessor` `babel-preset-es2015` `tape`.

throw new Error(messages.get("traverseVerifyNodeType", nodeType));
      ^
Error: You gave us a visitor for the node type "SafeMemberExpression" but it's not a valid type

**Comment by shuhei** [comment]
It seems like [src/patch-babel-types.js](https://github.com/shuhei/babel-plugin-null-safe-accessor/blob/master/src/patch-babel-types.js) is not patching the right `babel-types` module correctly.

Do you use npm 2 or npm 3? This plugin expects flat `node_modules` made by npm 3. Or it should be achieved by npm dedupe on npm 2.

**Comment by valleykid** [comment]
oh, I use npm 3...I've got it. thanks~

**Comment by valleykid** [comment]
In addition, I hope you can tell me how to write another plugin which implements the following requirements.

before:

``` jsx
ReactDOM.render(<name />, document.body);
```

after:

``` jsx
if(xxx){
    xxx(‘name’,  name, function(el){
        ReactDOM.render(<name />, el || document.body);
    });
} else {
    ReactDOM.render(<name />, document.body);
}
```

Looking forward to your reply~

**Comment by shuhei** [comment]
I recommend reading [Babel Plugin Handbook](https://github.com/thejameskyle/babel-plugin-handbook).

You'll do steps like the following:
1. Define a visitor to match the initial pattern. Know ASTs for the pattern. https://astexplorer.net/ with babylon6 `</>` will be useful.
2. Transform the initial pattern to the form that you want. `babel-generator` module will be useful.

**Comment by valleykid** [comment]
It's very useful, thanks a lot.

**Comment by shuhei** [comment]
No problem.

Sorry, `babel-template` instead of `babel-generator` in the step 2.
